// <auto-generated />
namespace Lythen.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class add20180628_2 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(add20180628_2));
        
        string IMigrationMetadata.Id
        {
            get { return "201806280330077_add20180628_2"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
